config/routes.rb
Rails.application.routes.draw do
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  post '/signout', to: 'sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :characters, only: %i[show index edit new]
  end
  resources :characters, only: %i[new create show index]

  namespace :admin do
    resources :jobs
    resources :races
  end

  # Defines the root path route ("/")
  root 'welcome#home'

  get '/auth/google_oauth2/callback', to: 'sessions#google_auth'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  # - Validations
  validates :name, :username, presence: true
  validates :username, uniqueness: true
  validates :password, presence: true, confirmation: true, on: :create

  # - Associations
  has_many :characters
  has_many :parties, through: :characters
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: %i[index new]
  before_action :set_user, only: %i[show edit update destroy]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "#{@user.name} was successfullty created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "#{@user.name} successfuly updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    flash[:notice] = "User #{@user.name} could not be found. Redirected to your homepage."
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find_by(id: params[:id])
    return unless @user.nil?

    redirect_to user_path(current_user), notice: 'User could not be found. Redirected to your homepage.'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for object do |f| %>
  <% if f.object.errors.present?%>
    <div style="color: red">
      <% f.object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <br>
      <% end %>
    </div>
  <% end %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <% if !@user.persisted? %>
    <div>
      <%= f.label :password%><br>
      <%= f.text_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation %><br>
      <%= f.text_field :password_confirmation  %>
    </div>
  <% end %>
  <%= f.check_box :admin %>
  <%= f.label :admin%>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div>
  <strong>Username: </strong><%= user.username %> <br>
  <strong><%= link_to 'Characters:', user_characters_path(user) %> </strong> Has <%= pluralize(user.characters.count, 'Character') %> <br>
  <% if characters %>
    <div>
      Alive:
      <ul>
        <% characters.is_alive.each do |character| %>
          <li><%= link_to character.name, user_character_path(user, character) %></li>
        <% end %>
      </ul>
      Dead:
      <ul>
        <% characters.is_dead.each do |character| %>
          <li><%= link_to character.name, user_character_path(user, character) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <strong>Parties:</strong> A member of <%= pluralize(user.parties.count, 'Party') %>
  <% if parties %>
    <div>
      <ul>
        <% parties.each do |party| %>
          <li><%= link_to party.name, '/' %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing <%= @user.name %></h1>
<%= render  'form',  object: @user %>

app/views/users/index.html.erb
<h1>User Index</h1>
<% @users.each do |user|%>
  <div>
    <%= render partial: 'user', locals: {user: user, parties: nil, characters: nil} %>
    <%= link_to "Go to #{user.name}'s page", user_path(user) %>
  </div>
  <br>
<% end %>

app/views/users/new.html.erb
<h1>New User Sign-up</h1>
<p>Enter your information below.</p>
<%= render 'form',  object: @user %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Page</h1>
<%= 'Admin' if @user.admin%>
<div>
  <%= render partial: 'user', locals: {user: @user, parties: @user.parties, characters: @user.characters}%>
</div>
<div class='navigation-links'>
  <%= link_to 'Back to Users', users_path %>
  <% if @user == current_user %>
    | <%= link_to 'Edit User', edit_user_path, method: :get%> </div>
  <div>
    <%= button_to 'Delete Profile', user_path, method: :delete%>
    <%= button_to 'Sign Out', signout_path, method: :post %>
  <% end %>
</div>