config/routes.rb
Rails.application.routes.draw do
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  post '/signout', to: 'sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :characters, only: %i[show index edit new]
  end
  resources :characters, only: %i[new create show index]

  namespace :admin do
    resources :jobs
    resources :races
  end

  # Defines the root path route ("/")
  root 'welcome#home'

  get '/auth/google_oauth2/callback', to: 'sessions#google_auth'
end

app/models/character.rb
class Character < ApplicationRecord
  # - Associations
  belongs_to :user
  belongs_to :party
  belongs_to :race
  belongs_to :job
  has_many :abilities
  has_many :benefits, through: :race

  # - nested Attributes
  accepts_nested_attributes_for :abilities

  # - Validations
  validates :name, presence: true, uniqueness: true

  # - scope
  scope :is_alive, -> { where(alive: true) }
  scope :is_dead, -> { where(alive: false) }

  # - Instance Methods
  def build_nested
    %w[Strength Dexterity Constitution Wisdom Charisma Inteligence].each do |i|
      abilities.build(name: i, value: 10)
    end
  end

  def get_racial_bonus(ability)
    bonus = benefits.find_by(name: ability.name)
    bonus.nil? ? '-' : bonus.value
  end

  def ability_with_modifier(ability)
    bonus = benefits.find_by(name: ability.name)
    bonus.nil? ? ability.value : (ability.value + bonus.value)
  end

  def ability_modifier(ability)
    ((ability_with_modifier(ability) - 10) / 2).floor
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :require_login
  before_action :find_user_from_params
  before_action :guard_user_characters, only: %i[new edit]

  def index
    # - Find user if params exist
    if params[:user_id]
      # - set character to user's characters
      @characters = Character.where(user_id: @user.id) unless @user.nil?
    else
      # - set characters to all characters
      @characters = @characters = Character.all
    end
  end

  def new
    # - create new character and build nested attributes
    @character = Character.new
    @character.build_nested
    # - if user parameter exist find user
    user = params[:user_id] ? User.find_by(id: params[:user_id]) : current_user
    # - redirect if user doesnt exist
    redirect_to user_characters_path(current_user) if user.nil?
    # -  set character's user equal to user from params or new
    @character.user = user
  end

  def create
    # - Create new character from params
    @character = Character.new(character_params)
    # - set user equal to User from database or current user based on params user id
    user = params[:user_id] ? User.find_by(id: params[:user_id]) : current_user
    # - redirect if user not found
    redirect_to users_path, notice: 'User could not be found.' if user.nil?
    # set character's user equalt to user
    @character.user = user

    if @character.save
      # - if user can be saved redirect with success
      redirect_to @character, notice: "#{@character.name} has been successfully created."
    else
      # - render form if save fails
      render :new, status: :unprocessable_entity
    end
  end

  def show
    if params[:user_id]
      @character = Character.find_by(id: params[:id], user_id: @user.id)
      (redirect_to user_characters_path(@user), notice: 'Character could not be found') if @character.nil?
    else
      @character = Character.find_by(id: params[:id])
      (redirect_to characters_path, notice: 'Character could not be found') if @character.nil?
    end
  end

  def edit
    @character = if params[:user_id]
                   Character.find_by(id: params[:id], user_id: @user.id)
                 else
                   Character.find_by(id: params[:id])
                 end

    (redirect_to user_characters_path(@user), notice: 'Character could not be found') if @character.nil?
  end

  def update
    @character = Character.find_by(id: params[:id])
    if @character.update(character_params)
      redirect_to @character, notice: "#{@character.name} has been successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @character = Character.find_by(id: params[:id])
    @character.destroy
    redirect_to characters_path
  end

  private

  def character_params
    params.require(:character).permit(:name, :race_id, :job_id, :party_id, abilities_attributes: %i[id value name])
  end

  def guard_user_characters
    return unless params[:user_id] && params[:user_id] != current_user.id.to_s

    redirect_to user_characters_path(User.find_by(id: params[:user_id]))
  end

  def find_user_from_params
    return unless params[:user_id]

    @user = User.find_by(id: params[:user_id])
    (redirect_to users_path, notice: 'User could not be found.') if @user.nil?
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_abilities.html.erb
<div>
  <strong>Abilities:</strong> <br>
  <table>
    <tr>
      <th> </th>
      <% character.abilities.each do |ability| %>
        <th><%= ability.name %></th>
      <% end %>
    </tr>
    <tr>
      <th><strong>Score:</strong></th>
      <% character.abilities.each do |ability| %>
        <td><%= ability.value %></td>
      <% end %>
    </tr>
    <tr>
      <th><strong>Race Bonus:</strong></th>
      <% character.abilities.each do |ability|%>
        <td><%= character.get_racial_bonus(ability)%></td>
      <% end %>
    </tr>
    <tr>
      <th><strong>Total:</strong></th>
      <% character.abilities.each do |ability| %>
        <td><%= character.ability_with_modifier(ability) %></td>
      <% end %>
    </tr>
    <tr>
      <th><strong>Modifier:</strong></th>
      <% character.abilities.each do |ability| %>
        <td><%= character.ability_modifier(ability) %></td>
      <% end %>
    </tr>
  </table>
</div>

app/views/characters/_character.html.erb
<div>
  <strong>Race:</strong> <%= character.race.name %> <br>
  <strong>Class:</strong> <%= character.job.name.capitalize %> <br>
  <strong>Party</strong>: <%= character.party.name%>
</div>

app/views/characters/_form.html.erb
<% if character.errors.any?%>
  <div id="error_explanation">
    <ul>
      <% character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <br>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for character do |f| %>
  <strong> <%= character.persisted? ? 'Change' : 'Add' %> Name:</strong> <br>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <br>
  <strong> <%= character.persisted? ? 'Change' : 'Add' %> Race:</strong><br>
  <%= f.label :race%>
  <%= f.collection_select :race_id, Race.order('name') ,:id, :name, {prompt: 'Select Race'} %>
  <br>
  <br>
  <strong> <%= character.persisted? ? 'Change' : 'Add' %> Class:</strong><br>
  <%= f.label :job %>
  <%= f.collection_select  :job_id, Job.order('name'), :id, :name, {prompt: 'Select Class'}%>
  <br>
  <br>
  <strong> <%= character.persisted? ? 'Change' : 'Add to' %> Party:</strong><br>
  <%= f.label :party %>
  <%= f.collection_select  :party_id, Party.all, :id, :name ,{prompt: 'Select Party'}%>
  <br>
  <br>
  <strong><%= character.persisted? ? 'Change' : 'Add' %> Ability Scores:</strong> <br>
  <%= f.fields_for :abilities do |field| %>
    <%= field.label :name %>
    <%= field.hidden_field :name%>
    <%= field.text_field :name, disabled: true %> <br>
    <%= field.label :value %>
    <%= field.number_field :value %>
    <br>
    <br>
  <% end %>
  <%= f.submit%>
<% end %>

app/views/characters/_party.html.erb
<div>
  <strong>Party Members:</strong> <br>
  <% @character.party.members.each do |member| %>
    <% if member != @character %>
      <%= link_to member.name, character_path(member) %> <br>
    <% end %>
  <% end %>
</div>

app/views/characters/edit.html.erb
<h1>Edit <%= @character.name %></h1>
<p>Edit character below:</p>
<%= render 'form', character: @character %>

app/views/characters/index.html.erb
<h1><%= @user ? "#{@user.name}'s " : 'All '%>Chracters</h1>
<br>
<% @characters.each do |character|%>
  <strong>Name: </strong><%= link_to character.name , user_character_path(character.user,character) %>
  <%= render 'character', character: character %>
  <br>
  <br>
<% end %>
<% if @user && current_user.id == @user.id %>
  <%= link_to "Create New Character ", new_user_character_path %>
<% end %>

app/views/characters/new.html.erb
<h1>Create New Character</h1>
<p>Enter new character information below:</p>
<%= render 'form', character: @character %>

app/views/characters/show.html.erb
<h1><%= @character.name %>'s Info</h1>
<h3>Owned by:<%= @character.user.name %></h3>
<%= render 'abilities', character: @character %>
<br>
<%= render 'character', character: @character %>
<br>
<%= render 'party', character: @character %>
<br>
<div>
  <% if @character.user == current_user %>
    <%= link_to "Edit #{@character.name}", edit_user_character_path(@character.id) %>
    <%= button_to 'Delete Character', character_path, method: :delete %>
  <% end %>
</div>